name: Build
on:
  - push
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm install --global pkg
      - name: Build
        run: pkg . --output mmcm-library-feedback-system
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mmcm-library-feedback-system-win
          path: mmcm-library-feedback-system.exe
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: mmcm-library-feedback-system.exe
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}